#
server:
  port: 8762

environments:
  development:
    datasource:
      mysqlDatabase: db_tamaraw
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: rootmysql
      MYSQL_PORT: 3306
      ENTITY_TO_SCAN: com.ascii274.login.entity
      URL: jdbc:mysql://localhost

# Configuration webapp directory
spring:
  thymeleaf:
    template-resolver-order: 0
    prefix: classpath:./webapp/WEB-INF/view/
#  web:
#    resources:
#      static-locations: classpath:./static/
#      static-locations: classpath./webapp/WEB-INF/view/
#

#      chain:
#        strategy:
#          content:
#            enabled: true
#            paths: "/**"

#custom directories

#  web:
#    resources:
#      static-locations: classpath:./resources/**
#  mvc:
#    static-path-pattern: "/resources/**"
#  web:
#    resources:
#      static-location: classpath:./webapp/
#  resources:
#    add-mapping: true

